[pytest]
minversion = 6.0
addopts = -ra -q --cov=tools --cov-report=term-missing
testpaths =
    tests
markers =
    accumulator: Unit tests for accumulator functionality
    math: Math-related unit tests
    pokemon_api: Pokemon API tests
    rest_api: REST API tests
    ui: UI tests